/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const MemoryCardIndexLazyImport = createFileRoute('/memory-card/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MemoryCardIndexLazyRoute = MemoryCardIndexLazyImport.update({
  path: '/memory-card/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/memory-card/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/memory-card/': {
      id: '/memory-card/'
      path: '/memory-card'
      fullPath: '/memory-card'
      preLoaderRoute: typeof MemoryCardIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/memory-card': typeof MemoryCardIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/memory-card': typeof MemoryCardIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/memory-card/': typeof MemoryCardIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memory-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memory-card'
  id: '__root__' | '/' | '/memory-card/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MemoryCardIndexLazyRoute: typeof MemoryCardIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MemoryCardIndexLazyRoute: MemoryCardIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/memory-card/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/memory-card/": {
      "filePath": "memory-card/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
