/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const MemoryCardManagerIndexLazyImport = createFileRoute(
  '/memory-card-manager/',
)()
const MemcarduinoFlasherIndexLazyImport = createFileRoute(
  '/memcarduino-flasher/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MemoryCardManagerIndexLazyRoute = MemoryCardManagerIndexLazyImport.update(
  {
    path: '/memory-card-manager/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/memory-card-manager/index.lazy').then((d) => d.Route),
)

const MemcarduinoFlasherIndexLazyRoute =
  MemcarduinoFlasherIndexLazyImport.update({
    path: '/memcarduino-flasher/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/memcarduino-flasher/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/memcarduino-flasher/': {
      id: '/memcarduino-flasher/'
      path: '/memcarduino-flasher'
      fullPath: '/memcarduino-flasher'
      preLoaderRoute: typeof MemcarduinoFlasherIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/memory-card-manager/': {
      id: '/memory-card-manager/'
      path: '/memory-card-manager'
      fullPath: '/memory-card-manager'
      preLoaderRoute: typeof MemoryCardManagerIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/memcarduino-flasher': typeof MemcarduinoFlasherIndexLazyRoute
  '/memory-card-manager': typeof MemoryCardManagerIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/memcarduino-flasher': typeof MemcarduinoFlasherIndexLazyRoute
  '/memory-card-manager': typeof MemoryCardManagerIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/memcarduino-flasher/': typeof MemcarduinoFlasherIndexLazyRoute
  '/memory-card-manager/': typeof MemoryCardManagerIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memcarduino-flasher' | '/memory-card-manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memcarduino-flasher' | '/memory-card-manager'
  id: '__root__' | '/' | '/memcarduino-flasher/' | '/memory-card-manager/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MemcarduinoFlasherIndexLazyRoute: typeof MemcarduinoFlasherIndexLazyRoute
  MemoryCardManagerIndexLazyRoute: typeof MemoryCardManagerIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MemcarduinoFlasherIndexLazyRoute: MemcarduinoFlasherIndexLazyRoute,
  MemoryCardManagerIndexLazyRoute: MemoryCardManagerIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/memcarduino-flasher/",
        "/memory-card-manager/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/memcarduino-flasher/": {
      "filePath": "memcarduino-flasher/index.lazy.tsx"
    },
    "/memory-card-manager/": {
      "filePath": "memory-card-manager/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
